blueprint:
  name: MQTTCarPresence2
  author: aderusha (Luma)
  description: Open garage door when car connects to Wi-Fi
  source_url: https://raw.githubusercontent.com/aderusha/MQTTCarPresence/master/MQTTCarPresence.yaml
  domain: automation
  homeassistant:
    min_version: 2023.6.2
  input:
    garage_door:
      name: Test Light
      description: This cover is the Garage Door
      selector:
        entity:
          filter:
          - domain:
            - cover
          multiple: false
    car_presence:
      name: Car Presence Sensor
      description: This sensor is the car's connection to the MQTT broker
      selector:
        entity:
          filter:
          - domain:
            - binary_sensor
          multiple: false
mode: single
trigger:
- platform: state
  entity_id: !input car_presence
  to: 'on'
- platform: state
  entity_id: !input car_presence
  to: 'off'
  for:
    minutes: 1
condition: []
action:
- choose:
  - conditions:
    - condition: state
      entity_id: !input car_presence
      state: 'on'
    - condition: state
      entity_id: !input garage_door
      state: on
    sequence:
    - service: cover.open_cover
      entity_id: !input garage_door
  - conditions:
    - condition: state
      entity_id: !input car_presence
      state: 'off'
    - condition: state
      entity_id: !input garage_door
      state: off
    sequence:
    - service: cover.close_cover
      entity_id: !input garage_door
  default: []
